# Generated by Django 3.0.1 on 2020-01-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique_for_date='publish'),
        ),
    ]
